import pyttsx3

engine = pyttsx3.init()
engine.setProperty('rate', 145)
engine.say("Hello Dear, This is a currency Convertor made by Team CoatCard , in this you can convert currency "
           "into various other currency")
engine.runAndWait()
engine.say("Lets start it for that from the given list please choose the currency that "
           "you want to convert to another one")
engine.runAndWait()
engine.say("one more thing is that the value of currency are updated on tenth of November 2022")
engine.runAndWait()
print("(INR for Indian Rupee),",
      "(GBP for Pounds),",
      "(EUR for Euros),",
      "(USD for Us Dollar),",
      "(CAD for Canadian Dollar),",
      "(CNY for Chinese Yuan),",
      "(RUB for Russian Rubal),",
      "(AED for United Arab Emirates Dirham),")
Currency1 = input("Please enter the currency code of the currency you want to convert: ")
engine.say("Please enter the currency code of the currency you want to convert")
engine.runAndWait()
Currency2 = input("Please enter the currency code of final currency: ")
engine.say("Please enter the currency code of final currency")
engine.runAndWait()
# Here is code for converting currency from Indian Rupee To another one
if Currency1 == "INR" and Currency2 == "USD":
    INR = int(input("Enter the amount of Indian Rupee: "))
    engine.say("Enter the amount of Indian Rupee")
    engine.runAndWait()
    value = "{:.2f}".format(INR / 81.31)
    print("after conversion the Indian Rupee In Us Dollar is : ", value)
    engine.say("after conversion the Indian Rupee In Us Dollar is", str(value))
    engine.runAndWait()
elif Currency1 == "INR" and Currency2 == "GBP":
    INR = int(input("Enter the amount of Indian Rupee: "))
    engine.say("Enter the amount of Indian Rupee")
    engine.runAndWait()
    value = "{:.2f}".format(INR / 92.29)
    print("after conversion the Indian Rupee In Pounds is : ", value)
    engine.say("after conversion the Indian Rupee In Pounds is", str(value))
    engine.runAndWait()
elif Currency1 == "INR" and Currency2 == "EUR":
    INR = int(input("Enter the amount of Indian Rupee: "))
    engine.say("Enter the amount of Indian Rupee")
    engine.runAndWait()
    value = "{:.2f}".format(INR / 81.41)
    print("after conversion the Indian Rupee In Euros is : ", value)
    engine.say("after conversion the Indian Rupee In Euros is", str(value))
    engine.runAndWait()
elif Currency1 == "INR" and Currency2 == "CAD":
    INR = int(input("Enter the amount of Indian Rupee: "))
    engine.say("Enter the amount of Indian Rupee")
    engine.runAndWait()
    value = "{:.2f}".format(INR / 60.16)
    print("after conversion the Indian Rupee In Canadian Dollar is : ", value)
    engine.say("after conversion the Indian Rupee In Canadian Dollar is", str(value))
    engine.runAndWait()
elif Currency1 == "INR" and Currency2 == "CNY":
    INR = int(input("Enter the amount of Indian Rupee: "))
    engine.say("Enter the amount of Indian Rupee")
    engine.runAndWait()
    value = "{:.2f}".format(INR / 11.23)
    print("after conversion the Indian Rupee In Chinese Yuan is : ", value)
    engine.say("after conversion the Indian Rupee In Chinese Yuan is", str(value))
    engine.runAndWait()
elif Currency1 == "INR" and Currency2 == "RUB":
    INR = int(input("Enter the amount of Indian Rupee: "))
    engine.say("Enter the amount of Indian Rupee")
    engine.runAndWait()
    value = "{:.2f}".format(INR / 1.32)
    print("after conversion the Indian Rupee In Russian Rubal is : ", value)
    engine.say("after conversion the Indian Rupee In Russian Rubal is", str(value))
    engine.runAndWait()
elif Currency1 == "INR" and Currency2 == "AED":
    INR = int(input("Enter the amount of Indian Rupee: "))
    engine.say("Enter the amount of Indian Rupee")
    engine.runAndWait()
    value = "{:.2f}".format(INR / 22.14)
    print("after conversion the Indian Rupee In United Arab Emirates Dirham is : ", value)
    engine.say("after conversion the Indian Rupee In United Arab Emirates Dirham is", str(value))
    engine.runAndWait()
# Here is code for converting currency from Pounds To another one
elif Currency1 == "GBP" and Currency2 == "INR":
    GBP = int(input("Enter the amount of Pounds: "))
    engine.say("Enter the amount of Pounds")
    engine.runAndWait()
    value = "{:.2f}".format(GBP / 0.011)
    print("after conversion the Pounds In Indian Rupee is : ", value)
    engine.say("after conversion the Pounds In Indian Rupee is", )
    engine.runAndWait()
elif Currency1 == "GBP" and Currency2 == "USD":
    GBP = int(input("Enter the amount of Pounds: "))
    engine.say("Enter the amount of Pounds")
    engine.runAndWait()
    value = "{:.2f}".format(GBP / 0.88)
    print("after conversion the Pounds In Us Dollar is : ", value)
    engine.say("after conversion the Pounds In Us Dollar is", )
    engine.runAndWait()
elif Currency1 == "GBP" and Currency2 == "EUR":
    GBP = int(input("Enter the amount of Pounds: "))
    engine.say("Enter the amount of Pounds")
    engine.runAndWait()
    value = "{:.2f}".format(GBP / 0.88)
    print("after conversion the Pounds In Euros is : ", value)
    engine.say("after conversion the Pounds In Euros is", )
    engine.runAndWait()
elif Currency1 == "GBP" and Currency2 == "CAD":
    GBP = int(input("Enter the amount of Pounds: "))
    engine.say("Enter the amount of Pounds")
    engine.runAndWait()
    value = "{:.2f}".format(GBP / 0.65)
    print("after conversion the Pounds In Canadian Dollar is : ", value)
    engine.say("after conversion the Pounds In Canadian Dollar is", )
    engine.runAndWait()
elif Currency1 == "GBP" and Currency2 == "CNY":
    GBP = int(input("Enter the amount of Pounds: "))
    engine.say("Enter the amount of Pounds")
    engine.runAndWait()
    value = "{:.2f}".format(GBP / 0.12)
    print("after conversion the Pounds In Chinese Yuan is : ", value)
    engine.say("after conversion the Pounds In Chinese Yuan is", )
    engine.runAndWait()
elif Currency1 == "GBP" and Currency2 == "RUB":
    GBP = int(input("Enter the amount of Pounds: "))
    engine.say("Enter the amount of Pounds")
    engine.runAndWait()
    value = "{:.2f}".format(GBP / 0.014)
    print("after conversion the Pounds In Russian Rubal is : ", value)
    engine.say("after conversion the Pounds In Russian Rubal is", )
    engine.runAndWait()
elif Currency1 == "GBP" and Currency2 == "AED":
    GBP = int(input("Enter the amount of Pounds: "))
    engine.say("Enter the amount of Pounds")
    engine.runAndWait()
    value = "{:.2f}".format(GBP / 0.24)
    print("after conversion the Pounds In United Arab Emirates Dirham is : ", value)
    engine.say("after conversion the Pounds In United Arab Emirates Dirham is", )
    engine.runAndWait()
# Here is code for converting currency from Euros To another one
elif Currency1 == "EUR" and Currency2 == "INR":
    EUR = int(input("Enter the amount of Euros: "))
    engine.say("Enter the amount of Euros")
    engine.runAndWait()
    value = "{:.2f}".format(EUR / 0.012)
    print("after conversion the Euros In Indian Rupee is : ", value)
    engine.say("after conversion the Euros In Indian Rupee is", )
    engine.runAndWait()
elif Currency1 == "EUR" and Currency2 == "GBP":
    EUR = int(input("Enter the amount of Euros: "))
    engine.say("Enter the amount of Euros")
    engine.runAndWait()
    value = "{:.2f}".format(EUR / 1.13)
    print("after conversion the Euros In Pounds is : ", value)
    engine.say("after conversion the Euros In Pounds is", )
    engine.runAndWait()
elif Currency1 == "EUR" and Currency2 == "USD":
    EUR = int(input("Enter the amount of Euros: "))
    engine.say("Enter the amount of Euros")
    engine.runAndWait()
    value = "{:.2f}".format(EUR / 1)
    print("after conversion the Euros In Us Dollar is : ", value)
    engine.say("after conversion the Euros In Us Dollar is", )
    engine.runAndWait()
elif Currency1 == "EUR" and Currency2 == "CAD":
    EUR = int(input("Enter the amount of Euros: "))
    engine.say("Enter the amount of Euros")
    engine.runAndWait()
    value = "{:.2f}".format(EUR / 0.74)
    print("after conversion the Euros In Canadian Dollar is : ", value)
    engine.say("after conversion the Euros In Canadian Dollar is", )
    engine.runAndWait()
elif Currency1 == "EUR" and Currency2 == "CNY":
    EUR = int(input("Enter the amount of Euros: "))
    engine.say("Enter the amount of Euros")
    engine.runAndWait()
    value = "{:.2f}".format(EUR / 0.14)
    print("after conversion the Euros In Chinese Yuan is : ", value)
    engine.say("after conversion the Euros In Chinese Yuan is", )
    engine.runAndWait()
elif Currency1 == "EUR" and Currency2 == "RUB":
    EUR = int(input("Enter the amount of Euros: "))
    engine.say("Enter the amount of Euros")
    engine.runAndWait()
    value = "{:.2f}".format(EUR / 0.016)
    print("after conversion the Euros In Russian Rubal is : ", value)
    engine.say("after conversion the Euros In Russian Rubal is", )
    engine.runAndWait()
elif Currency1 == "EUR" and Currency2 == "AED":
    EUR = int(input("Enter the amount of Euros: "))
    engine.say("Enter the amount of Euros")
    engine.runAndWait()
    value = "{:.2f}".format(EUR / 0.27)
    print("after conversion the Euros In United Arab Emirates Dirham is : ", value)
    engine.say("after conversion the Euros In United Arab Emirates Dirham is", )
    engine.runAndWait()
# Here is code for converting currency from US Dollar To another one
elif Currency1 == "USD" and Currency2 == "INR":
    USD = int(input("Enter the amount of US Dollar: "))
    engine.say("Enter the amount of US Dollar")
    engine.runAndWait()
    value = "{:.2f}".format(USD / 0.012)
    print("after conversion the US Dollar In Indian Rupee is : ", value)
    engine.say("after conversion the US Dollar In Indian Rupee is", )
    engine.runAndWait()
elif Currency1 == "USD" and Currency2 == "GBP":
    USD = int(input("Enter the amount of US Dollar: "))
    engine.say("Enter the amount of US Dollar")
    engine.runAndWait()
    value = "{:.2f}".format(USD / 1.13)
    print("after conversion the US Dollar In Pounds is : ", value)
    engine.say("after conversion the US Dollar In Pounds is", )
    engine.runAndWait()
elif Currency1 == "USD" and Currency2 == "EUR":
    USD = int(input("Enter the amount of US Dollar: "))
    engine.say("Enter the amount of US Dollar")
    engine.runAndWait()
    value = "{:.2f}".format(USD / 1)
    print("after conversion the US Dollar In Euros is : ", value)
    engine.say("after conversion the US Dollar In Euros is", )
    engine.runAndWait()
elif Currency1 == "USD" and Currency2 == "CAD":
    USD = int(input("Enter the amount of US Dollar: "))
    engine.say("Enter the amount of US Dollar")
    engine.runAndWait()
    value = "{:.2f}".format(USD / 0.74)
    print("after conversion the US Dollar In Canadian Dollar is : ", value)
    engine.say("after conversion the US Dollar In Canadian Dollar is", )
    engine.runAndWait()
elif Currency1 == "USD" and Currency2 == "CNY":
    USD = int(input("Enter the amount of US Dollar: "))
    engine.say("Enter the amount of US Dollar")
    engine.runAndWait()
    value = "{:.2f}".format(USD / 0.14)
    print("after conversion the US Dollar In Chinese Yuan is : ", value)
    engine.say("after conversion the US Dollar In Chinese Yuan is", )
    engine.runAndWait()
elif Currency1 == "USD" and Currency2 == "RUB":
    USD = int(input("Enter the amount of US Dollar: "))
    engine.say("Enter the amount of US Dollar")
    engine.runAndWait()
    value = "{:.2f}".format(USD / 0.016)
    print("after conversion the US Dollar In Russian Rubal is : ", value)
    engine.say("after conversion the US Dollar In Russian Rubal is", )
    engine.runAndWait()
elif Currency1 == "USD" and Currency2 == "AED":
    USD = int(input("Enter the amount of US Dollar: "))
    engine.say("Enter the amount of US Dollar")
    engine.runAndWait()
    value = "{:.2f}".format(USD / 0.27)
    print("after conversion the US Dollar In United Arab Emirates Dirham is : ", value)
    engine.say("after conversion the US Dollar In United Arab Emirates Dirham is", )
    engine.runAndWait()
# Here is code for converting currency from Canadian Dollar To another one
elif Currency1 == "CAD" and Currency2 == "INR":
    CAD = int(input("Enter the amount of Canadian Dollar: "))
    engine.say("Enter the amount of Canadian Dollar")
    engine.runAndWait()
    value = "{:.2f}".format(CAD / 0.017)
    print("after conversion the Canadian Dollar In Indian Rupee is : ", value)
    engine.say("after conversion the Canadian Dollar In Indian Rupee is", )
    engine.runAndWait()
elif Currency1 == "CAD" and Currency2 == "GBP":
    CAD = int(input("Enter the amount of Canadian Dollar: "))
    engine.say("Enter the amount of Canadian Dollar")
    engine.runAndWait()
    value = "{:.2f}".format(CAD / 1.54)
    print("after conversion the Canadian Dollar In Pounds is : ", value)
    engine.say("after conversion the Canadian Dollar In Pounds is", )
    engine.runAndWait()
elif Currency1 == "CAD" and Currency2 == "EUR":
    CAD = int(input("Enter the amount of Canadian Dollar: "))
    engine.say("Enter the amount of Canadian Dollar")
    engine.runAndWait()
    value = "{:.2f}".format(CAD / 1.35)
    print("after conversion the Canadian Dollar In Euros is : ", value)
    engine.say("after conversion the Canadian Dollar In Euros is", )
    engine.runAndWait()
elif Currency1 == "CAD" and Currency2 == "USD":
    CAD = int(input("Enter the amount of Canadian Dollar: "))
    engine.say("Enter the amount of Canadian Dollar")
    engine.runAndWait()
    value = "{:.2f}".format(CAD / 1.35)
    print("after conversion the Canadian Dollar In US Dollar is : ", value)
    engine.say("after conversion the Canadian Dollar In US Dollar is", )
    engine.runAndWait()
elif Currency1 == "CAD" and Currency2 == "CNY":
    CAD = int(input("Enter the amount of Canadian Dollar: "))
    engine.say("Enter the amount of Canadian Dollar")
    engine.runAndWait()
    value = "{:.2f}".format(CAD / 0.19)
    print("after conversion the Canadian Dollar In Chinese Yuan is : ", value)
    engine.say("after conversion the Canadian Dollar In Chinese Yuan is", )
    engine.runAndWait()
elif Currency1 == "CAD" and Currency2 == "RUB":
    CAD = int(input("Enter the amount of Canadian Dollar: "))
    engine.say("Enter the amount of Canadian Dollar")
    engine.runAndWait()
    value = "{:.2f}".format(CAD / 0.022)
    print("after conversion the Canadian Dollar In Russian Rubal is : ", value)
    engine.say("after conversion the Canadian Dollar In Russian Rubal is", )
    engine.runAndWait()
elif Currency1 == "CAD" and Currency2 == "AED":
    CAD = int(input("Enter the amount of Canadian Dollar: "))
    engine.say("Enter the amount of Canadian Dollar")
    engine.runAndWait()
    value = "{:.2f}".format(CAD / 0.37)
    print("after conversion the Canadian Dollar In United Arab Emirates Dirham is : ", value)
    engine.say("after conversion the Canadian Dollar In United Arab Emirates Dirham is", )
    engine.runAndWait()
# Here is code for converting currency from Chinese Yuan To another one
elif Currency1 == "CNY" and Currency2 == "INR":
    CNY = int(input("Enter the amount of Chinese Yuan: "))
    engine.say("Enter the amount of Chinese Yuan")
    engine.runAndWait()
    value = "{:.2f}".format(CNY / 0.089)
    print("after conversion the Chinese Yuan In Indian Rupee is : ", value)
    engine.say("after conversion the Chinese Yuan In Indian Rupee is", )
    engine.runAndWait()
elif Currency1 == "CNY" and Currency2 == "GBP":
    CNY = int(input("Enter the amount of Chinese Yuan: "))
    engine.say("Enter the amount of Chinese Yuan")
    engine.runAndWait()
    value = "{:.2f}".format(CNY / 8.22)
    print("after conversion the Chinese Yuan In Pounds is : ", value)
    engine.say("after conversion the Chinese Yuan In Pounds is", )
    engine.runAndWait()
elif Currency1 == "CNY" and Currency2 == "EUR":
    CNY = int(input("Enter the amount of Chinese Yuan: "))
    engine.say("Enter the amount of Chinese Yuan")
    engine.runAndWait()
    value = "{:.2f}".format(CNY / 7.24)
    print("after conversion the Chinese Yuan In Euros is : ", value)
    engine.say("after conversion the Chinese Yuan In Euros is", )
    engine.runAndWait()
elif Currency1 == "CNY" and Currency2 == "USD":
    CNY = int(input("Enter the amount of Chinese Yuan: "))
    engine.say("Enter the amount of Chinese Yuan")
    engine.runAndWait()
    value = "{:.2f}".format(CNY / 7.24)
    print("after conversion the Chinese Yuan In US Dollar is : ", value)
    engine.say("after conversion the Chinese Yuan In US Dollar is", )
    engine.runAndWait()
elif Currency1 == "CNY" and Currency2 == "CAD":
    CNY = int(input("Enter the amount of Chinese Yuan: "))
    engine.say("Enter the amount of Chinese Yuan")
    engine.runAndWait()
    value = "{:.2f}".format(CNY / 5.36)
    print("after conversion the Chinese Yuan In Canadian Dollar is : ", value)
    engine.say("after conversion the Chinese Yuan In Canadian Dollar is", )
    engine.runAndWait()
elif Currency1 == "CNY" and Currency2 == "RUB":
    CNY = int(input("Enter the amount of Chinese Yuan: "))
    engine.say("Enter the amount of Chinese Yuan")
    engine.runAndWait()
    value = "{:.2f}".format(CNY / 0.12)
    print("after conversion the Chinese Yuan In Russian Rubal is : ", value)
    engine.say("after conversion the Chinese Yuan In Russian Rubal is", )
    engine.runAndWait()
elif Currency1 == "CNY" and Currency2 == "AED":
    CNY = int(input("Enter the amount of Chinese Yuan: "))
    engine.say("Enter the amount of Chinese Yuan")
    engine.runAndWait()
    value = "{:.2f}".format(CNY / 1.97)
    print("after conversion the Chinese Yuan In United Arab Emirates Dirham is : ", value)
    engine.say("after conversion the Chinese Yuan In United Arab Emirates Dirham is", )
    engine.runAndWait()
# Here is code for converting currency from Russian Rubal To another one
elif Currency1 == "RUB" and Currency2 == "INR":
    RUB = int(input("Enter the amount of Russian Rubal: "))
    engine.say("Enter the amount of Russian Rubal")
    engine.runAndWait()
    value = "{:.2f}".format(RUB / 0.76)
    print("after conversion the Russian Rubal In Indian Rupee is : ", value)
    engine.say("after conversion the Russian Rubal In Indian Rupee is", )
    engine.runAndWait()
elif Currency1 == "RUB" and Currency2 == "GBP":
    RUB = int(input("Enter the amount of Russian Rubal: "))
    engine.say("Enter the amount of Russian Rubal")
    engine.runAndWait()
    value = "{:.2f}".format(RUB / 69.77)
    print("after conversion the Russian Rubal In Pounds is : ", value)
    engine.say("after conversion the Russian Rubal In Pounds is", )
    engine.runAndWait()
elif Currency1 == "RUB" and Currency2 == "EUR":
    RUB = int(input("Enter the amount of Russian Rubal: "))
    engine.say("Enter the amount of Russian Rubal")
    engine.runAndWait()
    value = "{:.2f}".format(RUB / 61.52)
    print("after conversion the Russian Rubal In Euros is : ", value)
    engine.say("after conversion the Russian Rubal In Euros is", )
    engine.runAndWait()
elif Currency1 == "RUB" and Currency2 == "USD":
    RUB = int(input("Enter the amount of Russian Rubal: "))
    engine.say("Enter the amount of Russian Rubal")
    engine.runAndWait()
    value = "{:.2f}".format(RUB / 61.45)
    print("after conversion the Russian Rubal In US Dollar is : ", value)
    engine.say("after conversion the Russian Rubal In US Dollar is", )
    engine.runAndWait()
elif Currency1 == "RUB" and Currency2 == "CAD":
    RUB = int(input("Enter the amount of Russian Rubal: "))
    engine.say("Enter the amount of Russian Rubal")
    engine.runAndWait()
    value = "{:.2f}".format(RUB / 45.45)
    print("after conversion the Russian Rubal In Canadian Dollar is : ", value)
    engine.say("after conversion the Russian Rubal In Canadian Dollar is", )
    engine.runAndWait()
elif Currency1 == "RUB" and Currency2 == "CNY":
    RUB = int(input("Enter the amount of Russian Rubal: "))
    engine.say("Enter the amount of Russian Rubal")
    engine.runAndWait()
    value = "{:.2f}".format(RUB / 8.53)
    print("after conversion the Russian Rubal In Chinese Yuan is : ", value)
    engine.say("after conversion the Russian Rubal In Chinese Yuan is", )
    engine.runAndWait()
elif Currency1 == "RUB" and Currency2 == "AED":
    RUB = int(input("Enter the amount of Russian Rubal: "))
    engine.say("Enter the amount of Russian Rubal")
    engine.runAndWait()
    value = "{:.2f}".format(RUB / 16.73)
    print("after conversion the Russian Rubal In United Arab Emirates Dirham is : ", value)
    engine.say("after conversion the Russian Rubal In United Arab Emirates Dirham is", )
    engine.runAndWait()
# Here is code for converting currency from the United Arab Emirates Dirham To another one
elif Currency1 == "AED" and Currency2 == "INR":
    AED = int(input("Enter the amount of United Arab Emirates Dirham: "))
    engine.say("Enter the amount of United Arab Emirates Dirham")
    engine.runAndWait()
    value = "{:.2f}".format(AED / 0.045)
    print("after conversion the United Arab Emirates Dirham In Indian Rupee is : ", value)
    engine.say("after conversion the United Arab Emirates Dirham In Indian Rupee is", )
    engine.runAndWait()
elif Currency1 == "AED" and Currency2 == "GBP":
    AED = int(input("Enter the amount of United Arab Emirates Dirham: "))
    engine.say("Enter the amount of United Arab Emirates Dirham")
    engine.runAndWait()
    value = "{:.2f}".format(AED / 4.17)
    print("after conversion the United Arab Emirates Dirham In Pounds is : ", value)
    engine.say("after conversion the United Arab Emirates Dirham In Pounds is", )
    engine.runAndWait()
elif Currency1 == "AED" and Currency2 == "EUR":
    AED = int(input("Enter the amount of United Arab Emirates Dirham: "))
    engine.say("Enter the amount of United Arab Emirates Dirham")
    engine.runAndWait()
    value = "{:.2f}".format(AED / 3.68)
    print("after conversion the United Arab Emirates Dirham In Euros is : ", value)
    engine.say("after conversion the United Arab Emirates Dirham In Euros is", )
    engine.runAndWait()
elif Currency1 == "AED" and Currency2 == "USD":
    AED = int(input("Enter the amount of United Arab Emirates Dirham: "))
    engine.say("Enter the amount of United Arab Emirates Dirham")
    engine.runAndWait()
    value = "{:.2f}".format(AED / 3.67)
    print("after conversion the United Arab Emirates Dirham In US Dollar is : ", value)
    engine.say("after conversion the United Arab Emirates Dirham In US Dollar is", )
    engine.runAndWait()
elif Currency1 == "AED" and Currency2 == "CAD":
    AED = int(input("Enter the amount of United Arab Emirates Dirham: "))
    engine.say("Enter the amount of United Arab Emirates Dirham")
    engine.runAndWait()
    value = "{:.2f}".format(AED / 2.72)
    print("after conversion the United Arab Emirates Dirham In Canadian Dollar is : ", value)
    engine.say("after conversion the United Arab Emirates Dirham In Canadian Dollar is", )
    engine.runAndWait()
elif Currency1 == "AED" and Currency2 == "CNY":
    AED = int(input("Enter the amount of United Arab Emirates Dirham: "))
    engine.say("Enter the amount of United Arab Emirates Dirham")
    engine.runAndWait()
    value = "{:.2f}".format(AED / 0.51)
    print("after conversion the United Arab Emirates Dirham In Chinese Yuan is : ", value)
    engine.say("after conversion the United Arab Emirates Dirham In Chinese Yuan is", )
    engine.runAndWait()
elif Currency1 == "AED" and Currency2 == "RUB":
    AED = int(input("Enter the amount of United Arab Emirates Dirham: "))
    engine.say("Enter the amount of United Arab Emirates Dirham")
    engine.runAndWait()
    value = "{:.2f}".format(AED / 0.060)
    print("after conversion the United Arab Emirates Dirham In Russian Rubal is : ", value)
    engine.say("after conversion the United Arab Emirates Dirham In Russian Rubal is", )
    engine.runAndWait()
else:
    print("Check the information You entered is correct or not")
print("Thankyou, For Using Me")
engine.say("Thankyou, For Using Me")
engine.runAndWait()
